# Application parameters
spring.application.name=studentdashboard

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/student_dashboard?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Dialect for MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Default Database: In-memory H2 Database for seamless out-of-the-box execution
#spring.datasource.url=jdbc:h2:mem:student_dashboard;DB_CLOSE_DELAY=-1
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driver-class-name=org.h2.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Enable OpenAPI documentation configurations
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
